/**
 * ProfilesInterface
 *
 * Defines the structure of a profile object.
 *
 * Used by:
 * - Profiles services and controllers
 *
 * Example:
 * {
 *   "id": "uuid",
 *   "profile": "admin"
 * }
 */
export interface ProfilesInterface {
    // Optional ID (auto-generated by the database)
    id?: string;

    // Profile name (e.g., admin, user)
    profile: string;
}
