/**
 * UsersInterface
 *
 * Defines the structure of a user object.
 *
 * Used by:
 * - Users services and controllers
 *
 * Example:
 * {
 *   "id": "uuid",
 *   "username": "john_doe",
 *   "email": "john@example.com",
 *   "password": "hashed_password",
 *   "birthdate": "2000-01-01",
 *   "profile": { "id": "uuid", "profile": "admin" }
 * }
 */
import { ProfilesInterface } from "./ProfilesInterface";

export interface UsersInterface {
    // Optional ID (generated by the database)
    id?: string;

    // Username
    username: string;

    // User email
    email: string;

    // Hashed password
    password: string;

    // Date of birth
    birthdate: Date;

    // Associated profile (relationship)
    profile: ProfilesInterface;
}
